### ISSUE TITLE
Environment variables should be extracted and exposed as static readonly strings

### ISSUE THREAD

**Issue by Paramethod** [xenial-io/Tasty#72]
Tasty uses these environment variables `TASTY_INTERACTIVE`, `TASTY_INTERACTIVE_CON_TYPE` and `TASTY_INTERACTIVE_CON_ID`. They are are currently hard coded in Xenial.Delicious.Remote.NamedPipeRemoteHook.CreateNamedPipeTransportStream and Xenial.Delicious.Cli.Internal.TastyCommander.ConnectToRemote. Should we extract them and expose as const in a default static class?

**Comment by biohazard999** [comment]
Yeah i thought about that, but until the second Transport is introduced i didnt want to mess around.

I am totally Not happy about the shape there, cause we should use a protocol url here like wss://xxx:xx but i don't know If there is a standard protocol Handler for named Pipes. That was way we can use the Uri Class and get rid of the second env var that increases complexity.

As for the envvar Key: IT should be a readonly string rather than const, cause if we ever Expose it to the User, we would break binary compat for users with floating nuget versions

**Comment by Paramethod** [comment]
Totally agree to using static readonly strings instead of const. Is Xenial.Core.EnvironmentVariables ok with you?

**Comment by biohazard999** [comment]
I keep every internal API right now in the default `Tasty.Delicious` namespace, so we don't pollute user namespace not too much. So And I have the feeling right now that those every will be used in some kind of transporty way, so I think `Xenial.Delicous.Protocols.EnvironmentVariables` or `Xenial.Delicous.Remote.EnvironmentVariables` would be fine until we decide when we make the API public.
